dist: xenial
language: ruby
rvm: 2.6.3
services:
  - postgresql
  - mysql
script: bundle exec rake test
before_install:
  - mysqladmin create groupdatesql_test
  - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql
  - createdb groupdatesql_test
notifications:
  email:
    on_success: never
    on_failure: change
