language: ruby
rvm: 2.5.1
sudo: false
script: bundle exec rake test
before_install:
  - gem install bundler
  - mysql -e 'create database groupdatesql_test;'
  - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql
  - psql -c 'create database groupdatesql_test;' -U postgres
notifications:
  email:
    on_success: never
    on_failure: change
