START TRANSACTION;

DROP FUNCTION IF EXISTS gd_version;
DROP FUNCTION IF EXISTS gd_second;
DROP FUNCTION IF EXISTS gd_minute;
DROP FUNCTION IF EXISTS gd_hour;
DROP FUNCTION IF EXISTS gd_day;
DROP FUNCTION IF EXISTS gd_week;
DROP FUNCTION IF EXISTS gd_week_mon;
DROP FUNCTION IF EXISTS gd_month;
DROP FUNCTION IF EXISTS gd_year;
DROP FUNCTION IF EXISTS gd_hour_of_day;
DROP FUNCTION IF EXISTS gd_day_of_week;

COMMIT;
